### ISSUE TITLE
Failed to compile on Linux

### ISSUE THREAD

**Issue by yzhao0527** [eddelbuettel/rcppbdt#3]
I am not familiar with the R build system.  When I tried to install this package either through install.packages or R CMD INSTALL, I got the following message:

    * installing to library ‘/myownpath/R/xxx-main/build’
    * installing *source* package ‘RcppBDT’ ...
    ** libs
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c RcppBDTdd.cpp -o RcppBDTdd.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [RcppBDTdd.o] Error 127 (ignored)
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c RcppBDTdt.cpp -o RcppBDTdt.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [RcppBDTdt.o] Error 127 (ignored)
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c RcppBDTdu.cpp -o RcppBDTdu.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [RcppBDTdu.o] Error 127 (ignored)
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c RcppBDTpt.cpp -o RcppBDTpt.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [RcppBDTpt.o] Error 127 (ignored)
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c RcppBDTtz.cpp -o RcppBDTtz.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [RcppBDTtz.o] Error 127 (ignored)
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c RcppExports.cpp -o RcppExports.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [RcppExports.o] Error 127 (ignored)
    I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/myownpath/R/xxx-main/build/Rcpp/include" -I"/myownpath/R/xxx-main/build/BH/include"      -c toPOSIXct.cpp -o toPOSIXct.o
    sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
    make: [toPOSIXct.o] Error 127 (ignored)
    -shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o RcppBDT.so RcppBDTdd.o RcppBDTdt.o RcppBDTdu.o RcppBDTpt.o RcppBDTtz.o RcppExports.o toPOSIXct.o -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR
    sh: line 2: -shared: command not found
    make: *** [RcppBDT.so] Error 127
    ERROR: compilation failed for package ‘RcppBDT’
    * removing ‘/myownpath/R/xxx-main/build/RcppBDT’

Instead of compiling cpp sources through:

    g++ -I/usr/lib64/microsoft-r/3.3/lib64/R/include

it used the wrong command with `g++ -` missing:

    I/usr/lib64/microsoft-r/3.3/lib64/R/include

I tried to install Rcpp and it succeeded.  Do you know what's going on here?

-----------------------------------------------------------------------

My temporary workaround is to `cd` into the `src` directory and manually compile all cpp files by:

    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c RcppBDTdd.cpp -o RcppBDTdd.o
    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c RcppBDTdt.cpp -o RcppBDTdt.o
    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c RcppBDTdu.cpp -o RcppBDTdu.o
    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c RcppBDTpt.cpp -o RcppBDTpt.o
    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c RcppBDTtz.cpp -o RcppBDTtz.o
    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c RcppExports.cpp -o RcppExports.o
    g++ -fPIC -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include/ -DU_STATIC_IMPLEMENTATION -I"/xxx/build/Rcpp/include" -I"/xxx/build/BH/include"      -c toPOSIXct.cpp -o toPOSIXct.o
    g++ -fPIC -shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o RcppBDT.so RcppBDTdd.o RcppBDTdt.o RcppBDTdu.o RcppBDTpt.o RcppBDTtz.o RcppExports.o toPOSIXct.o -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR

I also have to manually add `-fPIC` to build the shared library.

**Comment by eddelbuettel** [comment]
Briefly:

- I don't have Microsoft R so I cannot help you with particulars
- RcppBDT itself works just fine on Linux, see
    - Travis CI [build history](https://travis-ci.org/eddelbuettel/rcppbdt/builds)
    - CRAN [check results](https://cloud.r-project.org/web/checks/check_results_RcppBDT.html)
- You should never have gotten RcppBDT _without_ Rcpp as the latter is a declared dependency

So in short there is no issue here, beyond make something you may need to report to Microsoft,

**Comment by yzhao0527** [comment]
thank you, confirmed this is a bug in Microsoft-R-Open

https://github.com/Microsoft/microsoft-r-open/issues/17

**Comment by eddelbuettel** [comment]
Thanks for the follow-up, and the reference!  I left a message in their  threads https://github.com/Microsoft/microsoft-r-open/issues/11 and https://github.com/Microsoft/microsoft-r-open/issues/17 too.
