### ISSUE TITLE
Reason for using `delayedAssign` to initialize `bdt`

### ISSUE THREAD

**Issue by aviralg** [eddelbuettel/rcppbdt#4]
I am trying to follow the code of this package.
I am curious to know why `bdt` is defined used `delayedAssign` instead of normal assignment.

Is it because initialization is expensive and noticeably slow in interactive sessions? Wrapping it in a promise ensures that it gets initialized only when the user uses an API call that depends on it?

Since this is the main object which the library works with, this will get forced ultimately. Then why not pay the cost upfront and avoid wrapping it in a promise?

**Comment by eddelbuettel** [comment]
Hm, good question. I no longer recall.  There are two effects here -- Rcpp Modules (used by RcppBDT) are quirky.

As for you alternates: all good.  Go ahead and profile and report back :)  

More seriously, this may at some point have been driven too by CRAN Policy. When I do `git blame` on that segment I seem to have a commit message to that extend for the `setFromUTC()` part.

**Comment by eddelbuettel** [comment]
I will give you a firm "possibly".  I have a few more (small) packages with Rcpp Modules but this (which is old / was early) may be the only one where I decided to have an object created at load, which may have lead to this quagmire, and use of `delayedAssign()`.   In all fairness, the package is not widely used -- it was a test bed and my [anytime](https://github.com/eddelbuettel/anytime) package, also using Boost Date_time for its parser, is more widely used.

[ Also, if you haven't seen this, R has `system.time()` for quick and dirty timers. ]

**Comment by aviralg** [comment]
Thanks for the clarification.
